### ISSUE TITLE
Add an option to specify the theme?

### ISSUE THREAD

**Issue by zturtleman** [ashishb/wp2hugo#10]
An option to specify the address for the Hugo theme git repository to use might be useful.

The PaperMod theme used by wp2hugo isn't compatible with the Hugo version in Debian stable so this would allow skipping manually changing the theme before being able to test the generated site.

**Comment by ashishb** [comment]
@zturtleman Thanks for the feedback. Unfortunately, specifying theme isn't an option as quite a few options in this tool modify the features provided by `paperMod` theme. `paperMod` is the most popular theme, so, I don't think I made an esoteric pick either.

**Comment by zturtleman** [comment]
Okay, thanks for the reply. I found PaperMod 7.0 is still compatible with Debian's Hugo so I'll install it manually.
