### ISSUE TITLE
HTML to Markdown does not display manual line breaks

### ISSUE THREAD

**Issue by zturtleman** [ashishb/wp2hugo#12]
A list using `<br />` to separate lines in WordPress does not display line breaks in the generated Markdown. Adding two spaces to the end of lines with `<br />` forces a line break to be displayed. [Markdown reference](https://www.markdownguide.org/basic-syntax/#line-breaks)

WordPress XML export:
```
<!-- wp:paragraph -->
<p>First line<br />Second line<br />Third line</p>
<!-- /wp:paragraph -->
```
First line  
Second line  
Third line

Generated by wp2hugo:
```
First line
Second line
Third line
```
First line Second line Third line

Adding two spaces to the end of lines with `<br />` forces a line break to be displayed:
```
First line  
Second line  
Third line
```
First line  
Second line  
Third line

**Comment by ashishb** [comment]
@zturtleman 

What should be the right output of this?

```
<!-- wp:paragraph -->
<p>First line<br />Second line<br />Third line</p>
<!-- /wp:paragraph -->
```

As far as I know, there is no standard way to add non-paragraph line breaks in markdown.

**Comment by zturtleman** [comment]
For context, \<br /\> are generated by WordPress in paragraphs using shift+enter.

From the [Markdown standard](https://daringfireball.net/projects/markdown/syntax):
> When you _do_ want to insert a \<br /\> break tag using Markdown, you end a line with two or more spaces, then type return.

Converting this HTML to Markdown:
```
<!-- wp:paragraph -->
<p>First line<br />Second line<br />Third line</p>
<!-- /wp:paragraph -->
```

Should be this Markdown (with two spaces at the end of the first two lines):
```
First line  
Second line  
Third line
```

Using + to visual spaces, it would look like this:

```
First line++
Second line++
Third line
```

Though the Markdown itself should use spaces, not +.

**Comment by ashishb** [comment]
Thanks.
Would you like to send a PR @zturtleman ?

**Comment by zturtleman** [comment]
I provided more explanation on an [issue](https://github.com/JohannesKaufmann/html-to-markdown/issues/40) for the underlying library. I'm not planning to submit on a PR. It's not urgent for me personally.

**Comment by ashishb** [comment]
This has been fixed in https://github.com/ashishb/wp2hugo/commit/d28dd684e84a34a2b212d7a51a8c02334832eac5
