### ISSUE TITLE
Code for image is added to post summary and displayed as text

### ISSUE THREAD

**Issue by zturtleman** [ashishb/wp2hugo#13]
If a WordPress post begins with an image, wp2hugo adds the generated `{{< figure ... >}}` into the `summary` front matter of the post. It's displayed as text `{{< figure ... >}}` in the list of posts in PaperMod 7.0.

```
---
date: "2024-01-03T02:59:06+00:00"
guid: https://example.com/?p=1582
summary: |+
  {{< figure align=alignright width=204 src="https://example.com/wp-content/uploads/2024/01/example.jpg" alt="" >}}

  Hello world. This is a post.

title: Example
url: /2024/01/02/example/

---
{{< figure align=alignright width=204 src="/wp-content/uploads/2024/01/example.jpg" alt="" >}}

Hello world. This is a post.
```

Top-article summary display in PaperMod 7.0:

![Screenshot from 2024-03-26 21-17-40](https://github.com/ashishb/wp2hugo/assets/405505/f9f46438-a6d7-40b4-a7e5-e0557568d9a1)

**Comment by ashishb** [comment]
Fixed in 4feeaa526119fdcaa36a1d6f7b71a97438855a8b
