### ISSUE TITLE
Wordpress footnotes aren't handled

### ISSUE THREAD

**Issue by pgeorgi** [ashishb/wp2hugo#24]
Footnotes in the wordpress export look like this for me:

`text<sup data-fn="d47ee556-3faf-44c3-9949-3a1ae45f11f9" class="fn"><a href="#d47ee556-3faf-44c3-9949-3a1ae45f11f9" id="d47ee556-3faf-44c3-9949-3a1ae45f11f9-link">1</a></sup>`

with one of several wp:postmeta sections describing it like this:

```
                <wp:postmeta>
                <wp:meta_key><![CDATA[footnotes]]></wp:meta_key>
                <wp:meta_value><![CDATA[[{"content":"The Footnote Text","id":"d47ee556-3faf-44c3-9949-3a1ae45f11f9"}]]]></wp:meta_value>
                </wp:postmeta>
```

The conversion currently only keeps the `a href` portion, pointing to nowhere (that is, to the anchor `#d47...` which isn't present).

Not a priority for me, since my set of footnotes is so tiny that I just deal with them manually, but maybe something you want to implement?

**Comment by ashishb** [comment]
Thanks @pgeorgi.
Would you like to send a PR to fix this?
Alternatively, feel free to email me a sample file at ashishb[AT]ashishb.net

**Comment by ashishb** [comment]
Thanks.
This is not handled in https://github.com/ashishb/wp2hugo/commit/cdc3341a71a5ae9c975a83692b0ae9bef98f6825
