### ISSUE TITLE
make: *** [Makefile:9: build_prod] Error 1

### ISSUE THREAD

**Issue by amardeep-sidhu** [ashishb/wp2hugo#30]
Hi Ashish,

>>Download the wp2hugo tool from [releases]

This is no more there ?

Also, while trying to build from the source, it somehow doesn't work for me.

```bash
[user01@primhost wp2hugo]$ make build_prod
# Shrink binary by removing symbol and DWARF table
# Ref: https://lukeeckley.com/post/useful-go-build-flags/
go build -v -ldflags="-s -w" -o bin/wp2hugo ./cmd/wp2hugo
go: go.mod requires go >= 1.22.1 (running go 1.21.11; GOTOOLCHAIN=local)
make: *** [Makefile:9: build_prod] Error 1
[user01@primhost wp2hugo]$
```

**Comment by amardeep-sidhu** [comment]
Sorry for the trouble. I got it. The source link should point to https://github.com/ashishb/wp2hugo/tags

I am able to download the binary and run it but it fails with an error:

```{"level":"debug","time":1722955203,"message":"Output: wp_output"}
{"level":"debug","siteName":"generated-2024-08-06-20-10-03","time":1722955203,"message":"Setting up Hugo site"}
{"level":"debug","time":1722955203,"message":"Running Hugo setup commands"}
{"level":"fatal","time":1722955204,"message":"Error: error running Hugo setup commands: exit status 1"}```

**Comment by ashishb** [comment]
@amardeep-sidhu you need to install `hugo` first.
I will add more logging around it to make the error more obvious in https://github.com/ashishb/wp2hugo/commit/ede76f6cea84eba06acfc644d2ecf0c8eceee057
