### ISSUE TITLE
Can I ignore the error during `download-media` option on?

### ISSUE THREAD

**Issue by whusnoopy** [ashishb/wp2hugo#33]
I have a 20 years old blog, which migrated many times via many hosts, it running on self host WordPress now.

The links for some attachments is not reachable, if I run wp2hugo with `download-media` option on, the trans will ended on first failure when it try to get the file but failed.

Is there any way to ignore error during download, and put a placehold for them?

**Comment by ashishb** [comment]
This has been fixed in https://github.com/ashishb/wp2hugo/commit/9d34d1f2c55a6eeae5ac5693e352fabe0ddfaa68 via `continue-on-media-download-error` boolean flag
