### ISSUE TITLE
Download all media attachments

### ISSUE THREAD

**Issue by aurelienpierre** [ashishb/wp2hugo#50]
As mentionned in #49, only WP image attachments (and only the ones found in pages ?) are downloaded to Hugo assets.  I think useful to download all attachements, regardless of MIME type, for backup reasons as well as to cover niche embedding of attachments in pages (using shortcodes or `post_meta` values).

Right now, the mitigation solution is to copy/paste all the `/wp-content/uploads` content, but that will also import all various thumbnail sizes of images, which will not be re-used by Hugo and only pollute assets.

Using proper download from the `.xml` WordPress export at least gives the opportunity of fetching only full-size or original images.

**Comment by ashishb** [comment]
> (and only the ones found in pages ?) 

This is intentional.
I don't want to download all the clutter that one might have accumulated, at least, by default.

So, we want to start from the page and download media attachments linked from those pages.
