### ISSUE TITLE
Support WooCommerce products ?

### ISSUE THREAD

**Issue by aurelienpierre** [ashishb/wp2hugo#52]
I have an e-shop, as part of a website to migrate, run with WooCommerce. This particular store is a bit overkill, as products are manufactured upon order and with a fair amount of personnalization, which leads anyway to client <-> business emails to confirm specifications, price and shipping (aka not a retail situation – plus prices may vary in time due to materials).

Meaning the whole store would better be run as a static front, where product pages contain email forms pre-filled with product info, and invoices are handled manually upon client inquiries by email. Hence why Hugo.

WooCommerce products use `product_variations` a bit like `posts` use `attachments`. That's to say, a proper import would need to remap them using frontmatter fields in place of `wp_meta` keys.

Anyway, I have to code it. I understand it's pretty niche. My question is if you are interested by the feature @ashishb ?

Aside from this particular case, it might be useful to export WooCommerce products as basic .md pages (as exchange format), including thumbnail, title, description and other properties.

**Comment by ashishb** [comment]
@aurelienpierre there is `wpparser` and there is `hugogenerator`.
They are almost independent of each other.
Feel free to add `woocommerceparser` to this project.

**Comment by aurelienpierre** [comment]
I have investigated this. WooCommerce products are simply WP custom post types, with custom taxonomies (`product_cat`, `product_tag`, etc.). As such, a `woocommerceparser` would duplicate a large amount of code from `wpparser`. What would be a sane way to share common methods (like date parsing and such) between both modules ?
