### ISSUE TITLE
Windows Definder finds Trojan:Win32/Wacatac.H!ml in wp2hugo_Windows_x86_64.zip for version 1.6.0 

### ISSUE THREAD

**Issue by jgraber** [ashishb/wp2hugo#53]
Hi,
When I tried to run your tool, Windows Defender blocked the pre-compiled exe and warned me that it contains the Trojan:Win32/Wacatac.H!ml trojan in [wp2hugo_Windows_x86_64.zip](https://github.com/ashishb/wp2hugo/releases/download/1.6.0/wp2hugo_Windows_x86_64.zip).

It may be a false positive, but maybe you can check if something went wrong with the compilation.

**Comment by ashishb** [comment]
Hi Johnny

Thanks for the report.
The binaries are auto-generated via the `goreleaser` script.
The only scenario that this might happen is if Github Action's Windows machines themselves are infected.
Unlikely but possible.
