### ISSUE TITLE
Post time isn't correctly exported

### ISSUE THREAD

**Issue by amardeep-sidhu** [ashishb/wp2hugo#54]
Thank you for writing this very useful utility. I noticed an issue that post time isn't exported correctly. I have my timezone in wordpress set to GMT + 5:30 but it exports only the GMT time. Not sure if it is intentional. 

e.g. one post shows the date and time as date: "2021-03-10T12:47:34+00:00". But the actual time is 6:17 PM IST.

**Comment by ashishb** [comment]
> e.g. one post shows the date and time as date: "2021-03-10T12:47:34+00:00". But the actual time is 6:17 PM IST.

These are the same times, aren't they?

`2021-03-10T12:47:34+00:00` or
`2021-03-10T18:177:34+05:30`

**Comment by amardeep-sidhu** [comment]
Sorry for not being clear enough.

Wordpress post time is `6:17 PM IST (or 2021-03-10T12:47:34+05:30)`

When I export using wp2hugo, the timestamp that gets exported is

`date: "2021-03-10T12:47:34+00:00"`

**Comment by ashishb** [comment]
> Wordpress post time is 6:17 PM IST (or 2021-03-10T12:47:34+05:30)

Are you sure?
I think `6:17 PM IST` should be `2021-03-10T6:17:34+05:30`

**Comment by amardeep-sidhu** [comment]
I think, you are right. Then we can say that the date part isn't exported correctly.

Here is my scenario:

wp2hugo exports the date as `date: "2021-03-10T12:47:34+00:00"`

and in Hugo it shows as `March 10, 2021 at 12:47 PM`

I used another exporter and it exported the date as `date: '2021-03-10T18:17:34+05:30'`

And in Hugo the date shows as `March 10, 2021 at 6:17 PM` which is correct.

**Comment by ashishb** [comment]
I believe it is taking your server's timezone for the display.
Where is your site deployed?

**Comment by amardeep-sidhu** [comment]
ah, sounds right. I am yet to deploy it but the VM where I am running wp2hugo is in GMT timezone `Tue Sep 17 07:46:26 GMT 2024`

So could be because of that. Thank you
