### ISSUE TITLE
-download-media fails when posts are embedding images from other hosts

### ISSUE THREAD

**Issue by Taschi120** [ashishb/wp2hugo#65]
I am trying to run wp2hugo on an export from my wordpress dot com blog. Some posts on that blog reference images hosted on an even older blog of mine, or on Flickr. The conversion with `-download-media`  flag fails on these posts, with error messages like this:

> 03:53:56PM DBG media_downloader.go:25 > Downloading from URL destFilePath=generated-2024-10-10-15-53-29/static/https://c1.staticflickr.com/1/314/REDACTED.jpg
> 03:53:56PM ERR hugo_gen_setup.go:453 > error downloading media file error="error creating directory: mkdir generated-2024-10-10-15-53-29/static/https:: The filename, directory name, or volume label syntax is incorrect." mediaLink=https://c1.staticflickr.com/1/314/REDACTED.jpg pageLink=https://REDACTED.wordpress.com/2017/01/21/<redacted>/

**Comment by Taschi120** [comment]
Note: If the `-continue-on-media-download-error` option is used, the generated Markdown pages will correctly embed these images via their original URL, which is in 99.9% of all cases the correct thing to do. It would thus be an acceptable fix in my opinion to simply skip downloading any media from fully qualified URLs.

**Comment by ashishb** [comment]
@Taschi120 thanks for pointing out. Can you please email me a sample WordPress export that I can experiment with to fix this? My email is ashishb AT ashishb DOT net

**Comment by ashishb** [comment]
Fixed in https://github.com/ashishb/wp2hugo/commit/64df053f840fa6b3ea64f98b673f31cdcc38595e
