### ISSUE TITLE
Fails on filename too long

### ISSUE THREAD

**Issue by djotaku** [ashishb/wp2hugo#66]
04:25:14PM FTL main.go:43 > Error: error opening page file: open /home/ermesa/tmp/generated-2024-10-11-16-25-01/content/posts/reviews-the-ultimate-history-of-video-games-from-pong-to-pokemon-the-story-behind-the-craze-that-touched-our-lives-and-changed-the-world-food-processor-perfection-75-amazing-ways-to-use-the-most-powerful-tool-in-your-kitchen-planet-barbecue-309-recipes-60-countries-prepare-to-meet-thy-doom-and-more-true-gaming-stories-abaddon-s-gate-damnation-alley-the-improbable-rise-of-singularity-girl-the-perfect-cookie-your-ultimate-guide-to-foolproof-cookies-brownies-and-bars-words-of-radiance.md: file name too long

**Comment by djotaku** [comment]
Also:

04:31:52PM FTL main.go:43 > Error: error opening page file: open /home/ermesa/tmp/generated-2024-10-11-16-31-33/content/posts/reviews-the-future-is-japanese-science-fiction-futures-and-brand-new-fantasies-from-and-about-japan-cibola-burn-edgedancer-sixth-of-the-dusk-the-virtuous-feats-of-the-indomitable-miss-trafalgar-and-the-erudite-lady-boone-the-churn-altered-america-steampunk-stories-dungeon-hacks-how-nethack-angband-and-other-roguelikes-changed-the-course-of-video-games-nemesis-games-legion.md: file name too long

But I'm changing the names so that it can work in my case. Just thought it was something you might want to fix.

**Comment by ashishb** [comment]
Thanks for pointing out.
If you have a fix in mind feel free to send.
I am not planning to prioritize fixing it for now.
