### ISSUE TITLE
When there are quotes in an image file's title, they cause issues

### ISSUE THREAD

**Issue by djotaku** [ashishb/wp2hugo#67]
In this one I got the error:  got positional parameter 'The'. Cannot mix named and positional parameters

[columbus-day-2016-at-the-park.md](https://github.com/user-attachments/files/17347346/columbus-day-2016-at-the-park.md)

In this one: got positional parameter 'OH'. Cannot mix named and positional parameters

[concert-photography-for-amateurs.md](https://github.com/user-attachments/files/17347348/concert-photography-for-amateurs.md)

If you look in each, those are in the image "title" tag and have quotes. So by having double-quotes, it's throwing off Hugo's parser. Maybe your code needs to change those to escaped quotation marks?

**Comment by djotaku** [comment]
I can confirm that manually escaping the quotation marks fixes things

**Comment by ashishb** [comment]
Thanks for reporting this.
It should be fixed in https://github.com/ashishb/wp2hugo/commit/cefbbbe841cc418efdbde43a6291936eea783eb1
