### ISSUE TITLE
Support for [gallery] shortcodes with no specific IDs

### ISSUE THREAD

**Issue by leewillis77** [ashishb/wp2hugo#68]
Following on from #64 I wanted to provide a sample export file, and demonstration of how that *should* be handled. A gallery shortcode with no files will create a gallery of all attached media.

See the sample export XML:
https://www.dropbox.com/scl/fi/4d9egeagaqaeq3r3c6mb5/leewillis.WordPress.2024-10-12.xml?rlkey=hmpubv4gxlgpehsyeva0n1t4w&dl=1

Here's the real WordPress page that generated it showing the gallery:
https://www.leewillis.co.uk/product-options-for-wp-e-commerce/

**Comment by ashishb** [comment]
Thanks @leewillis77 do you know how are images like https://www.leewillis.co.uk/wp-content/uploads/2011/08/screenshot-1.png linked to https://www.leewillis.co.uk/product-options-for-wp-e-commerce/?

I can see attachments like https://www.leewillis.co.uk/wp-content/uploads/2011/08/screenshot-1.png in your XML
I can see pages like https://www.leewillis.co.uk/product-options-for-wp-e-commerce/
However, it is not obvious to me how are they linked to each other in the WordPress XML.
I need that linkage to create a list of IDs for generating the correct gallery code in this case.

**Comment by leewillis77** [comment]
@ashishb The `post_parent` of the attachment is the ID of the page:

![Screenshot 2024-11-18 at 07 17 20](https://github.com/user-attachments/assets/6894f691-7d1d-4955-b023-bf59bc76f252)
![Screenshot 2024-11-18 at 07 18 21](https://github.com/user-attachments/assets/eb27afed-8681-4ad5-b664-f13d17e0ac3b)

**Comment by ashishb** [comment]
Thanks @leewillis77 for pointing that out.
This feature has been added in https://github.com/ashishb/wp2hugo/commit/6b550e80d2892d5e4c56c002277a5e78446fe23d
