### ISSUE TITLE
Multiple posts with the same post title are overwritten

### ISSUE THREAD

**Issue by zturtleman** [ashishb/wp2hugo#7]
wp2hugo 1.0 only creates one file in `content/posts/*.md` for a given post title even if the WordPress XML export has multiple posts with the same title. The other posts with the same post title are not transferred to the generated Hugo site.

WordPress automatically appends a number to the slug (the post title in the URL). For example, three posts with the title "Status Update" would have URLs like:
- example.com/2022/01/01/status-update/
- example.com/2023/01/01/status-update-2/
- example.com/2024/01/01/status-update-3/

Maybe wp2hugo could append a number to the filename if the file already exists in `content/posts/*.md`.

**Comment by ashishb** [comment]
@zturtleman good catch. Can you give me a sample website to test?
I fixed it in https://github.com/ashishb/wp2hugo/commit/770e17a3a30f1d13291a9a3c5b3e3e86d74729ae but I am not sure if the fix is correct.

**Comment by zturtleman** [comment]
All the wp2hugo 1.1 closed issues work now, thank you. Sorry, no sample website.

One cosmetic difference compared to WordPress is that WordPress starts additional names at 2 while wp2hugo starts at 1. It doesn't affect website usability though.

Generated filenames:
* status-update.md is example.com/2022/01/01/status-update/
* status-update-1.md is example.com/2023/01/01/status-update-2/
* status-update-2.md is example.com/2024/01/01/status-update-3/

Maybe this line:
https://github.com/ashishb/wp2hugo/blob/770e17a3a30f1d13291a9a3c5b3e3e86d74729ae/src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go#L171
