### ISSUE TITLE
FTL main.go:43 > Error: error running Hugo setup commands: exit status 127

### ISSUE THREAD

**Issue by memo** [ashishb/wp2hugo#70]
Hi, I just downloaded wp2hugo, and I'm getting the error above. I'm on windows and have hugo installed and on the path. Log below.
(I tried outputting to both the default /tmp, and also a subdir).

> 11:38:45AM DBG main.go:50 > Reading website export source=memoakten.WordPress.2024-10-14.xml
> 11:38:45AM DBG wp_parser_setup.go:366 > Attachment URL attachmentURL=https://www.memo.tv/wpmemo/wp-content/uploads/2018/04/image-placeholder-27-min.jpg
> 11:38:45AM DBG wp_parser_setup.go:366 > Attachment URL attachmentURL=https://www.memo.tv/wpmemo/wp-content/uploads/2018/04/image-placeholder-8-min.jpg
> 11:38:45AM DBG wp_parser_setup.go:366 > Attachment URL attachmentURL=https://www.youtube.com/watch?v=mA0l2NauzUc
> 11:38:45AM DBG wp_parser_setup.go:366 > Attachment URL attachmentURL=https://www.memo.tv/wpmemo/wp-content/uploads/2018/04/image-placeholder-9-min.jpg
> 11:38:45AM DBG wp_parser_setup.go:366 > Attachment URL attachmentURL=https://www.memo.tv/wpmemo/wp-content/uploads/2018/04/image-placeholder-20-min.jpg
> 
> 
> ...
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Deep Meditations at ME by Melia 2019" type=ml-slider
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77041 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77041 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77041 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77041 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Deep Meditations at Sonar+D 2019" type=ml-slider
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77070 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77070 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77070 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77070 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77070 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77070 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77070 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77070 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77070 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77070 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77070 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77070 - image" type=ml-slide
> 11:38:45AM INF wp_parser_setup.go:267 > Ignoring item title="Slider 77070 - image" type=ml-slide
> 11:38:45AM WRN wp_parser_setup.go:621 > ignoring empty footnote link=https://www.memo.tv/help/
> 11:38:46AM WRN wp_parser_setup.go:621 > ignoring empty footnote link=https://www.memo.tv/artworks/
> 11:38:46AM WRN wp_parser_setup.go:223 > Empty content title=Artworks
> 11:38:46AM WRN wp_parser_setup.go:223 > Empty content title="Selected Projects"
> 11:38:46AM WRN wp_parser_setup.go:223 > Empty content title="Selected Performances"
> 11:38:46AM WRN wp_parser_setup.go:223 > Empty content title="Selected Exhibitions &amp; Installations"
> 11:38:46AM WRN wp_parser_setup.go:223 > Empty content title="Client Commissions &amp; Collaborations"
> 11:38:46AM WRN wp_parser_setup.go:223 > Empty content title=Home
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Webcam Piano (2007, 2010)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Gold (2008)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="iScream for iPhone (2009)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Body Paint (2009)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Reincarnation (2009)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="My Secret Heart (2008)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Amoeba dance (2007)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Ecstasy (1997, 2003)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="The Morning After (2003)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="I can't wait to grow up (2002)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="abstractshit.com (2003)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Simple Harmonic Motion #14 (WIP, 2016)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Depeche Mode - Fragile Tension (2009)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Blaze - The Streetdance Show (2010)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="ofxMSAOpenCL (2009)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="qcMSABadTV (2007)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="MSAPhysics (2008)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="MSAFluid (2008)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title=NFT type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Waves: The Abiotechnogenesis Collection (2021)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Waves (2014-)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Simple Harmonic Motion #12 for 16 Percussionists at RNCM (2015)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Simple Harmonic Motion #11 for Light at Blenheim Palace (2014)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="The Black Quadrilateral: Protective Edge (2014)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Equilibrium (2014)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Simple Harmonic Motion #8, #9 (2013)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Reducible Complexity (2013)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Just for hits - Mutation in the mind (2013)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Laser Forest (2013)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Meet your creator (2012)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Forms (2011)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Simple Harmonic Motion #5 (2011)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="The Measures Taken (2014)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="McLaren P1 Light Painting (2012)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Sony PlayStation3 Video Store (2011)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Deutsche Bank Hong Kong (2010)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Wombats - Techno Fan (2010)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Laser Fingers (2013)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Mocap2Web (2012)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Volumetric Slitscanning (2012)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Learning to See: Hello, World! (2017)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Dirty Data (2017)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="FIGHT! (2017)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Pattern Recognition (2016)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="#EpicMonetGuy (2016)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="All watched over by machines of loving grace: Deepdream edition (2015)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Narrative (2015)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Journey through the layers of the mind (2015)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Petita DumDum Techa (2016)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Dronery (2016)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="@WordOfMath (2016)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Learning to dream: Supergan! (2017)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Optimising for Beauty (2017)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Learning to see: We are made of star dust (2017)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Learning to dream (2017)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Learning to see: Gloomy Sunday (2017)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="@WordOfMathBias (2016)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="ofxMSATensorFlow (2016)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="ofxMSAmcts (2015)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Learning to see: Interactive (2017)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Learning to See Series (2017-)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Deep Meditations: A brief history of almost everything (2018)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Grannma MagNet - Granular Neural Music & Audio with Magnitude Networks (2018)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Simple Harmonic Motion (2011-)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Ultrachunk (2018)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="We are all connected (WIP, 2019)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Nimiia Cétiï (2018)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Superhuman Artificial Intelligence (2019)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Deep Meditations at Sonar+D (2019)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Deep Meditations at ME by Melia Atrium (2019)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Deep Meditations at Kennin-ji Temple (2019)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="#EpicGanGuy (2019)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="#BigGAN Music Video Studies (2018)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Learning to see: True Colors (2020)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="#StayHomeSaveLives (2020)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Deep Meditations: We are all connected (Studies, 2020)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Max Cooper - Morphosis (2019)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Bibtex Title Generator (2017)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Tomorrow (2018)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Simple Harmonic Motion for Light at Signal Festival (2019)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Keeper of our collective consciousness (2014-2020)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Body Paint at The Electric Castle 2019" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="The Awesome Machinery of Nature: We are all connected (2021)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="All Watched Over By Machines Of Loving Grace (2021)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Deeper Meditations (2021)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Distributed Consciousness (2021)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Deep Meditations: Abiogenesis (2018-2020)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Distributed Consciousness Installation (2022)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Deep Life (2022)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="PixlFlippr (fxhash generative NFT) (2021)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Waves: Serenity (fxhash generative NFT) (2022)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Quantum Vacuum (fxhash generative NFT) (2021)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="STRATA (fxhash generative NFT) (2022)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="A Strange Loop (fxhash generative NFT) (2022)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Waves 2.0: Terra (2023)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="All Watched Over by Machines of Loving Grace + Deeper Meditations #1-#6 (2021)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Layers of Perception (2024)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Boundaries (2024)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="Embodied Simulation - Tribeca (2024)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title="SUPERRADIANCE (2024)" type=portfolio
> 11:38:46AM INF wp_parser_setup.go:267 > Ignoring item title=Welcome type=portfolio
> 11:38:46AM DBG wp_parser_setup.go:446 > getNavigationLinks navigationLinks=21
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Artworks","Type":"page","URL":"https://www.memo.tv/artworks/"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Performances","Type":"page","URL":"https://www.memo.tv/performances/"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Exhibitions","Type":"page","URL":"https://www.memo.tv/exhibitions/"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Commissions","Type":"page","URL":"https://www.memo.tv/commissions/"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Research","Type":"page","URL":"https://www.memo.tv/research/"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Talks","Type":"page","URL":"https://www.memo.tv/talks/"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Texts","Type":"page","URL":"https://www.memo.tv/texts/"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Info","Type":"page","URL":"https://www.memo.tv/"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Bio","Type":"custom","URL":"https://www.memo.tv/info#bio"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Statement","Type":"custom","URL":"https://www.memo.tv/info#statement"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"PhD","Type":"custom","URL":"https://www.memo.tv/info#phd"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Awards","Type":"custom","URL":"https://www.memo.tv/info#awards"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Juries","Type":"custom","URL":"https://www.memo.tv/info#juries"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Collections","Type":"custom","URL":"https://www.memo.tv/info#collections"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Publications","Type":"custom","URL":"https://www.memo.tv/info#publications"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Shows","Type":"custom","URL":"https://www.memo.tv/info#shows"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Talks","Type":"custom","URL":"https://www.memo.tv/info#talks"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Press","Type":"custom","URL":"https://www.memo.tv/info#press"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Education","Type":"custom","URL":"#education"}
> 11:38:46AM DBG wp_parser_setup.go:461 > Navigation link link={"Title":"Headshots","Type":"custom","URL":"#headshots"}
> 11:38:46AM INF wp_parser_setup.go:293 > WebsiteInfo: Memo Akten numAttachments=1471 numCategories=1 numPages=20 numPosts=8 numTags=0
> 11:38:46AM DBG main.go:68 > Output: .\out
> 11:38:46AM DBG hugo_gen_setup.go:157 > Setting up Hugo site siteName=generated-2024-10-14-11-38-46
> 11:38:46AM DBG hugo_gen_setup.go:180 > Running Hugo setup commands
> 11:38:47AM ERR hugo_gen_setup.go:187 > error running Hugo setup commands error="exit status 127" cmd="hugo version && cd .\\out && hugo new site generated-2024-10-14-11-38-46 --format yaml && cd generated-2024-10-14-11-38-46 && git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1 && rm -rf themes/PaperMod/.git themes/PaperMod/.github && echo \"theme: 'PaperMod'\">> hugo.yaml && hugo" output=
> 11:38:47AM FTL main.go:43 > Error: error running Hugo setup commands: exit status 127

**Comment by ashishb** [comment]
> hugo version && cd .\out && hugo new site generated-2024-10-14-11-38-46 --format yaml && cd generated-2024-10-14-11-38-46 && git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1 && rm -rf themes/PaperMod/.git themes/PaperMod/.github && echo "theme: 'PaperMod'">> hugo.yaml && hugo

It is one of these commands, can you run them one by one and see which fails?

- hugo version 
- cd .\out 
- hugo new site generated-2024-10-14-11-38-46 --format yaml
- cd generated-2024-10-14-11-38-46 
- git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1 
- rm -rf themes/PaperMod/.git themes/PaperMod/.github
- echo "theme: 'PaperMod'">> hugo.yaml && hugo

**Comment by ashishb** [comment]
https://github.com/ashishb/wp2hugo/commit/a0cf6b2493472458a56591cbdfd237c593d54f15 should make the failure more explicit.
