### ISSUE TITLE
Hugo Deprecation Error

### ISSUE THREAD

**Issue by acrosman** [ashishb/wp2hugo#72]
Thank you for taking the time to create this tool.  I'm hopeful I'll be able to use it to transition my site, but I'm running into challenges with a deprecation error from Hugo when it reaches the setup phase:

`11:30:42PM ERR hugo_gen_setup.go:187 > error running Hugo setup commands error="exit status 1" cmd="hugo version && cd /tmp && hugo new site generated-2024-10-23-23-30-41 --format yaml && cd generated-2024-10-23-23-30-41 && git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1 && rm -rf themes/PaperMod/.git themes/PaperMod/.github && echo \"theme: 'PaperMod'\">> hugo.yaml && hugo" output="hugo v0.136.4+extended darwin/arm64 BuildDate=2024-10-22T08:35:58Z VendorInfo=brew\nCongratulations! Your new Hugo site was created in /tmp/generated-2024-10-23-23-30-41.\n\nJust a few more steps...\n\n1. Change the current directory to /tmp/generated-2024-10-23-23-30-41.\n2. Create or install a theme:\n   - Create a new theme with the command \"hugo new theme <THEMENAME>\"\n   - Or, install a theme from https://themes.gohugo.io/\n3. Edit hugo.yaml, setting the \"theme\" property to the theme name.\n4. Create new content with the command \"hugo new content <SECTIONNAME>/<FILENAME>.<FORMAT>\".\n5. Start the embedded web server with the command \"hugo server --buildDrafts\".\n\nSee documentation at https://gohugo.io/.\nStart building sites … \nhugo v0.136.4+extended darwin/arm64 BuildDate=2024-10-22T08:35:58Z VendorInfo=brew\n\nERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Implement taxonomy 'social' or use .Site.Params.Social instead.\nTotal in 18 ms\nError: error building site: logged 1 error(s)\n"`

Hugo Version: hugo v0.136.4+extended darwin/arm64 BuildDate=2024-10-22T08:35:58Z VendorInfo=brew
wp2hugo Release: 1.8.1
OS: Mac OS Sonoma on Arm

The result is a stub site in the provided location, but none of the context was converted.

**Comment by grnxp** [comment]
Hello,

I think I managed to get it working by modifying the `hugo_gen_setup.go` file and specifying that the bash shell must locate itself into the new site folder. 

You can find the commit here - https://github.com/ashishb/wp2hugo/pull/73/commits/6416be756905d7d94af243175dfd6b373c9f09e6 and the merge request here - https://github.com/ashishb/wp2hugo/pull/73 

I don't know if it will have an impact on older versions of Hugo or other systems though, but it seems to work well with the one brew installed on my system (macOS Sequoia 15.0.1) : 

```bash
$ hugo version                             
hugo v0.134.1+extended darwin/arm64 BuildDate=2024-09-05T10:17:50Z VendorInfo=brew
```

**Comment by acrosman** [comment]
Looks like this was recently fixed but not in a released version. A build from source does not have this issue.

**Comment by ashishb** [comment]
Thanks @grnxp I will make a new release.
