### ISSUE TITLE
Media Downloads with /// prefix fail

### ISSUE THREAD

**Issue by acrosman** [ashishb/wp2hugo#74]
Under some conditions, when http or https are possible to load the page, URLs prefixed with `///` are meant to indicate that the current protocol should be used with the domain that follows. 

So a reference to `///example.org/path/to/media` should get the current protocol prepended.  However the `downloadPageMedia` function just checks for one `/` and then prepends the current domain with a protocol. 

In my case there are references to images in the form:
`///example.org/wp-content/uploads/2016/07/sampleImage.png`
Your (very much appreciated) tool attempted to pull the file from:
`https://example.org///example.org/wp-content/uploads/2016/07/sampleImage.png`
Instead of:
`https://example.org/wp-content/uploads/2016/07/sampleImage.png`

The issue appears to stem from [here](https://github.com/ashishb/wp2hugo/blob/a0cf6b2493472458a56591cbdfd237c593d54f15/src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go#L421) where it checks for prefixes but doesn't include `///` and then doesn't re-add `url.Scheme` in that case.

**Comment by acrosman** [comment]
I don't have a great deal of go experience, but I'll try to get a PR together.

**Comment by ashishb** [comment]
Thanks @acrosman are you sure about this though? I thought that `//example.com/path/to/media` is used to convey current protocol
