### ISSUE TITLE
Category / Tag bug

### ISSUE THREAD

**Issue by joshbressers** [ashishb/wp2hugo#76]
I use a few categories and a lot of tags on my wp site. When I generate the markdown, the categories data is wrong, and it just a mirror of the tags data

I *think* I found the problem, but I'm not an expert
https://github.com/ashishb/wp2hugo/blob/main/src/wp2hugo/internal/wpparser/wp_parser_setup.go#L340
`pageCategories = append(pageTags, NormalizeCategoryName(category.Value))`

When I change that line to 

`pageCategories = append(pageCategories, NormalizeCategoryName(category.Value))`

my categories are correct, but my home page is just loading the list of all blogs instead of the landing page it used to. But that could be some other problem with my wordpress site :)

**Comment by ashishb** [comment]
Thanks for pointing it out.
This has been fixed in #77
