### ISSUE TITLE
Using -download-media option, URLs are hardcoded to ashishb.net

### ISSUE THREAD

**Issue by zturtleman** [ashishb/wp2hugo#8]
wp2hugo 1.0's -download-media option tries to downloads all site-local image URLs from ashishb.net.

For a WordPress instance at example.com, `https://example.com/wp-content/2024/01/image.png` will be downloaded from `https://ashishb.net//wp-content/2024/01/image.png`. It saves the HTML for the ashishb.net 404 page as image.png.

Possibly due to this code:
https://github.com/ashishb/wp2hugo/blob/c1391d721ca6f23d9e60f393df5754bed359f9c4/src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go#L265-L267

**Comment by ashishb** [comment]
Good catch.
Fixed in https://github.com/ashishb/wp2hugo/commit/1d56b86257eb53f80d830030d161f2d41d6d6f3b
