### ISSUE TITLE
Image with parenthesis in URL cannot be fetched

### ISSUE THREAD

**Issue by habi** [ashishb/wp2hugo#81]
Aeons ago I made [a blog post](https://habi.gna.ch/2003/07/26/canyoning/) including the image `https://habi.gna.ch/blog/images/Picture(2).jpg`

When calling `wp2hugo` with 
```bash
./src/wp2hugo/bin/wp2hugo -source habignach.WordPress.2024-10-29.xml  -download-media
```
the process fails with 
```bash
05:33:50PM DBG hugo_gen_setup.go:412 > Embedded media links links=1 page=https://habi.gna.ch/2003/07/26/canyoning/
05:33:50PM DBG hugo_gen_setup.go:416 > Downloading media files links=1
05:33:50PM INF media_cache_setup.go:33 > media https://habi.gna.ch/blog/images/Picture(2 will be fetched
05:33:50PM FTL main.go:43 > Error: error fetching media file https://habi.gna.ch/blog/images/Picture(2: error fetching media https://habi.gna.ch/blog/images/Picture(2: 404 Not Found
```

I think the fetching link needs escaping of the parenthesis :)

`grep "Picture(2" habignach.WordPress.2024-10-29.xml` returns `<a href="http://habi.gna.ch/blog/images/Picture(2).jpg"><img src="http://habi.gna.ch/blog/images/Picture(2)-tm.jpg" height="288" width="352" align="middle" border="2" hspace="0" vspace="0" alt="" longdesc="" /></a><p>` BTW

**Comment by ashishb** [comment]
Thanks @habi , can you please email me habignach.WordPress.2024-10-29.xml at ashishb [AT] ashishb [DOT] net to reproduce and fix this?

**Comment by ashishb** [comment]
Fixed in https://github.com/ashishb/wp2hugo/pull/84

**Comment by habi** [comment]
> can you please email me habignach.WordPress.2024-10-29.xml

Happy to do that for a next time, or you can download a semi-recent export here: https://github.com/habi/blog
